/**
 * @tekton/core - CSS Generator Tests
 * Test-First: Define expected behavior for CSS Variables generation
 * [SPEC-COMPONENT-001-A] [CSS-GENERATION]
 */

import { describe, it, expect } from 'vitest';
import { generateThemeCSS } from '../src/css-generator.js';
import type { ThemeWithTokens, SemanticTokens, ComponentTokens } from '../src/tokens.js';

// ============================================================================
// Test Fixture: Complete Theme with 3-Layer Tokens
// ============================================================================

const mockThemeWithTokens: ThemeWithTokens = {
  id: 'test-theme',
  name: 'Test Theme',
  description: 'A test theme for CSS generation',
  brandTone: 'professional',
  colorPalette: {
    primary: { l: 0.6, c: 0.15, h: 220 },
  },
  typography: {
    fontFamily: 'Inter, sans-serif',
    fontScale: 'medium',
    headingWeight: 700,
    bodyWeight: 400,
  },
  componentDefaults: {
    borderRadius: 'medium',
    density: 'comfortable',
    contrast: 'medium',
  },
  tokens: {
    atomic: {
      color: {
        blue: {
          '400': '#60a5fa',
          '500': '#3b82f6',
          '600': '#2563eb',
        },
        neutral: {
          '50': '#f9fafb',
          '100': '#f3f4f6',
          '200': '#e5e7eb',
          '900': '#111827',
        },
      },
      spacing: {
        '4': '16px',
        '8': '32px',
      },
      radius: {
        md: '8px',
        lg: '12px',
      },
      typography: {
        body: {
          fontSize: '16px',
          lineHeight: '24px',
          fontWeight: '400',
        },
        heading: {
          fontSize: '24px',
          lineHeight: '32px',
          fontWeight: '700',
        },
      },
      shadow: {
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1)',
      },
    },
    semantic: {
      background: {
        page: 'atomic.color.neutral.50',
        surface: '#ffffff',
        elevated: '#ffffff',
        muted: 'atomic.color.neutral.100',
        inverse: 'atomic.color.neutral.900',
      },
      foreground: {
        primary: 'atomic.color.neutral.900',
        secondary: '#6b7280',
        muted: '#9ca3af',
        inverse: '#ffffff',
        accent: 'atomic.color.blue.500',
      },
      border: {
        default: 'atomic.color.neutral.200',
        muted: 'atomic.color.neutral.100',
        focus: 'atomic.color.blue.500',
        error: '#ef4444',
      },
      surface: {
        primary: '#ffffff',
        secondary: 'atomic.color.neutral.50',
        tertiary: 'atomic.color.neutral.100',
        inverse: 'atomic.color.neutral.900',
      },
    },
    component: {
      button: {
        primary: {
          background: 'semantic.foreground.accent',
          foreground: '#ffffff',
          border: 'semantic.foreground.accent',
          hover: {
            background: 'atomic.color.blue.600',
            foreground: '#ffffff',
          },
          active: {
            background: '#1d4ed8',
          },
          disabled: {
            background: 'semantic.background.muted',
            foreground: 'semantic.foreground.muted',
          },
        },
      },
      input: {
        background: 'semantic.background.surface',
        foreground: 'semantic.foreground.primary',
        border: 'semantic.border.default',
        placeholder: 'semantic.foreground.muted',
        focus: {
          border: 'semantic.border.focus',
          ring: 'atomic.color.blue.500',
        },
        error: {
          border: 'semantic.border.error',
          ring: '#ef4444',
        },
        disabled: {
          background: 'semantic.background.muted',
          foreground: 'semantic.foreground.muted',
        },
      },
      card: {
        background: 'semantic.background.surface',
        foreground: 'semantic.foreground.primary',
        border: 'semantic.border.default',
        shadow: 'atomic.shadow.md',
      },
    },
  },
};

// ============================================================================
// CSS Generation Tests - Structure
// ============================================================================

describe('generateThemeCSS - Structure', () => {
  it('should generate valid CSS output', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toBeTruthy();
    expect(css).toContain(':root {');
    expect(css).toContain('}');
  });

  it('should include header comments with theme info', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toContain('Generated by Tekton');
    expect(css).toContain('Theme: test-theme');
    expect(css).toContain('Do not edit manually');
  });

  it('should organize CSS by layer with comments', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toContain('Layer 1: Atomic Tokens');
    expect(css).toContain('Layer 2: Semantic Tokens');
    expect(css).toContain('Layer 3: Component Tokens');
  });
});

// ============================================================================
// CSS Generation Tests - Atomic Layer
// ============================================================================

describe('generateThemeCSS - Atomic Layer', () => {
  it('should generate color variables with correct naming', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Atomic tokens use --atomic- prefix
    expect(css).toContain('--atomic-color-blue-500: #3b82f6;');
    expect(css).toContain('--atomic-color-blue-600: #2563eb;');
    expect(css).toContain('--atomic-color-neutral-50: #f9fafb;');
    expect(css).toContain('--atomic-color-neutral-900: #111827;');
  });

  it('should generate spacing variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Atomic tokens use --atomic- prefix
    expect(css).toContain('--atomic-spacing-4: 16px;');
    expect(css).toContain('--atomic-spacing-8: 32px;');
  });

  it('should generate radius variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Atomic tokens use --atomic- prefix
    expect(css).toContain('--atomic-radius-md: 8px;');
    expect(css).toContain('--atomic-radius-lg: 12px;');
  });

  it('should generate typography variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Typography uses --atomic-typography- prefix
    expect(css).toContain('--atomic-typography-body-size: 16px;');
    expect(css).toContain('--atomic-typography-body-line-height: 24px;');
    expect(css).toContain('--atomic-typography-body-weight: 400;');
    expect(css).toContain('--atomic-typography-heading-size: 24px;');
  });

  it('should generate shadow variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Shadow uses --atomic-shadow- prefix
    expect(css).toContain('--atomic-shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1);');
    expect(css).toContain('--atomic-shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1);');
  });
});

// ============================================================================
// CSS Generation Tests - Semantic Layer
// ============================================================================

describe('generateThemeCSS - Semantic Layer', () => {
  it('should generate background semantic variables with resolved values', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Semantic tokens use --atomic-semantic- prefix
    expect(css).toContain('--atomic-semantic-background-page:'); // Resolves atomic.color.neutral.50
    expect(css).toContain('--atomic-semantic-background-surface:');
    expect(css).toContain('--atomic-semantic-background-muted:'); // Resolves atomic.color.neutral.100
  });

  it('should generate foreground semantic variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Semantic tokens use --atomic-semantic- prefix
    expect(css).toContain('--atomic-semantic-foreground-primary:'); // Resolves atomic.color.neutral.900
    expect(css).toContain('--atomic-semantic-foreground-accent:'); // Resolves atomic.color.blue.500
  });

  it('should generate border semantic variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: Semantic tokens use --atomic-semantic- prefix
    expect(css).toContain('--atomic-semantic-border-default:'); // Resolves atomic.color.neutral.200
    expect(css).toContain('--atomic-semantic-border-focus:'); // Resolves atomic.color.blue.500
  });
});

// ============================================================================
// CSS Generation Tests - Component Layer
// ============================================================================

describe('generateThemeCSS - Component Layer', () => {
  it('should generate button component variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toContain('--button-primary-background: #3b82f6;'); // Resolves semantic.foreground.accent
    expect(css).toContain('--button-primary-foreground: #ffffff;');
    expect(css).toContain('--button-primary-hover-background: #2563eb;'); // Resolves atomic.color.blue.600
  });

  it('should generate nested component variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toContain('--input-focus-border:');
    expect(css).toContain('--input-focus-ring:');
    expect(css).toContain('--input-error-border:');
    expect(css).toContain('--input-disabled-background:');
  });

  it('should generate card component variables', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toContain('--card-background: #ffffff;');
    expect(css).toContain('--card-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1);');
  });
});

// ============================================================================
// CSS Generation Tests - Dark Mode
// ============================================================================

describe('generateThemeCSS - Dark Mode', () => {
  it('should generate dark mode CSS when darkMode is defined', () => {
    const themeWithDarkMode: ThemeWithTokens = {
      ...mockThemeWithTokens,
      darkMode: {
        tokens: {
          semantic: {
            background: {
              page: 'atomic.color.neutral.900',
            } as SemanticTokens['background'],
          },
          component: {
            button: {
              primary: {
                background: 'atomic.color.blue.400',
              } as ComponentTokens['button']['primary'],
            },
          },
        },
      },
    };

    const css = generateThemeCSS(themeWithDarkMode);

    expect(css).toContain('.dark {');
    expect(css).toContain('Dark Mode Overrides');
  });

  it('should override semantic tokens in dark mode', () => {
    const themeWithDarkMode: ThemeWithTokens = {
      ...mockThemeWithTokens,
      darkMode: {
        tokens: {
          semantic: {
            background: {
              page: 'atomic.color.neutral.900',
              surface: 'atomic.color.neutral.900',
            } as SemanticTokens['background'],
          },
          component: {},
        },
      },
    };

    const css = generateThemeCSS(themeWithDarkMode);

    expect(css).toContain('.dark {');
    expect(css).toContain('--background-page: #111827;'); // Dark mode override
  });

  it('should override component tokens in dark mode', () => {
    const themeWithDarkMode: ThemeWithTokens = {
      ...mockThemeWithTokens,
      darkMode: {
        tokens: {
          semantic: {},
          component: {
            button: {
              primary: {
                background: 'atomic.color.blue.400',
              } as ComponentTokens['button']['primary'],
            },
          },
        },
      },
    };

    const css = generateThemeCSS(themeWithDarkMode);

    expect(css).toContain('.dark {');
    expect(css).toContain('--button-primary-background: #60a5fa;'); // Dark mode override
  });

  it('should not generate dark mode CSS if darkMode is undefined', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).not.toContain('.dark {');
    expect(css).not.toContain('Dark Mode Overrides');
  });
});

// ============================================================================
// CSS Generation Tests - Edge Cases
// ============================================================================

describe('generateThemeCSS - Edge Cases', () => {
  it('should handle direct color values (non-references)', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // v2.1: semantic.background.surface is direct '#ffffff'
    // Semantic tokens use --atomic-semantic- prefix
    expect(css).toContain('--atomic-semantic-background-surface: #ffffff;');
  });

  it('should resolve multi-level references correctly', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // component.button.primary.background → semantic.foreground.accent → atomic.color.blue.500 → #3b82f6
    expect(css).toContain('--button-primary-background: #3b82f6;');
  });

  it('should handle deeply nested component properties', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    expect(css).toContain('--button-primary-disabled-background:');
    expect(css).toContain('--button-primary-disabled-foreground:');
  });

  it('should produce valid CSS syntax (no syntax errors)', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // Check for balanced braces
    const openBraces = (css.match(/{/g) || []).length;
    const closeBraces = (css.match(/}/g) || []).length;
    expect(openBraces).toBe(closeBraces);

    // Check for proper semicolons
    const declarations = css.match(/--[^:]+:[^;]+;/g) || [];
    expect(declarations.length).toBeGreaterThan(0);
  });
});

// ============================================================================
// CSS Generation Tests - Zero Hardcoded Values
// ============================================================================

describe('generateThemeCSS - Zero Hardcoded Values', () => {
  it('should not contain hardcoded color values in component layer', () => {
    const css = generateThemeCSS(mockThemeWithTokens);

    // Extract component layer CSS
    const componentLayerStart = css.indexOf('Layer 3: Component Tokens');
    const componentLayerEnd = css.indexOf('.dark {') !== -1 ? css.indexOf('.dark {') : css.length;
    const componentCSS = css.substring(componentLayerStart, componentLayerEnd);

    // All component values should be resolved references
    const componentVars = componentCSS.match(/--[^:]+: ([^;]+);/g) || [];

    // Verify values are resolved (not references like "semantic.foreground.accent")
    componentVars.forEach(varDecl => {
      expect(varDecl).not.toContain('atomic.');
      expect(varDecl).not.toContain('semantic.');
      expect(varDecl).not.toContain('component.');
    });
  });
});
