/**
 * CSS Generator
 * Wraps token-contract CSS generation with export-specific options
 */

import {
  generateCSSFromTokens,
  generateDarkModeCSS,
  mergeLightAndDarkCSS,
  type SemanticToken,
  type CompositionToken,
} from '@tekton/token-contract';

export interface CSSGeneratorOptions {
  semantic: SemanticToken;
  composition?: CompositionToken;
  includeDarkMode: boolean;
  minify?: boolean;
}

/**
 * Generate CSS export content from tokens
 * Optionally includes dark mode variants
 */
export function generateCSSExport({
  semantic,
  composition,
  includeDarkMode,
  minify = false,
}: CSSGeneratorOptions): string {
  // Generate light mode CSS
  const lightCSS = generateCSSFromTokens({ semantic, composition });

  if (!includeDarkMode) {
    return minify ? minifyCSS(lightCSS) : formatCSS(lightCSS);
  }

  // Generate dark mode CSS
  const darkCSS = generateDarkModeCSS(semantic);

  // Merge light and dark CSS
  const fullCSS = mergeLightAndDarkCSS(lightCSS, darkCSS);

  return minify ? minifyCSS(fullCSS) : formatCSS(fullCSS);
}

/**
 * Format CSS with consistent indentation
 */
function formatCSS(css: string): string {
  const header = `/**
 * Design Tokens - Generated by Tekton Studio
 * @generated
 */

`;
  return header + css;
}

/**
 * Minify CSS by removing whitespace
 */
function minifyCSS(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '') // Remove comments
    .replace(/\s+/g, ' ') // Collapse whitespace
    .replace(/\s*{\s*/g, '{') // Remove space around {
    .replace(/\s*}\s*/g, '}') // Remove space around }
    .replace(/\s*:\s*/g, ':') // Remove space around :
    .replace(/\s*;\s*/g, ';') // Remove space around ;
    .trim();
}

/**
 * Generate CSS variable usage example
 */
export function generateCSSUsageExample(): string {
  return `/* Example Usage */
.button {
  background-color: var(--tekton-primary-500);
  color: var(--tekton-neutral-50);
  border-radius: var(--tekton-border-radius);
  padding: var(--tekton-spacing-padding);
}

.button:hover {
  background-color: var(--tekton-primary-600);
}

.button:focus {
  outline: 2px solid var(--tekton-primary-300);
  outline-offset: 2px;
}`;
}
