import { describe, it, expect } from 'vitest';
import { generateCSSExport, generateCSSUsageExample } from '@/lib/export/css-generator';
import type { SemanticToken } from '@tekton/token-contract';

describe('css-generator', () => {
  const mockTokens: SemanticToken = {
    primary: {
      '500': { l: 0.53, c: 0.15, h: 220 },
      '600': { l: 0.45, c: 0.15, h: 220 },
    },
  };

  describe('generateCSSExport', () => {
    it('generates CSS with header comment', () => {
      const result = generateCSSExport({
        semantic: mockTokens,
        includeDarkMode: false,
      });

      expect(result).toContain('Design Tokens - Generated by Tekton Studio');
      expect(result).toContain(':root');
    });

    it('includes CSS variables for tokens', () => {
      const result = generateCSSExport({
        semantic: mockTokens,
        includeDarkMode: false,
      });

      expect(result).toContain('--tekton-primary-500');
      expect(result).toContain('--tekton-primary-600');
      expect(result).toContain('oklch');
    });

    it('generates dark mode CSS when enabled', () => {
      const result = generateCSSExport({
        semantic: mockTokens,
        includeDarkMode: true,
      });

      expect(result).toContain('[data-theme="dark"]');
    });

    it('minifies CSS when minify option is true', () => {
      const result = generateCSSExport({
        semantic: mockTokens,
        includeDarkMode: false,
        minify: true,
      });

      // Minified CSS should not have newlines inside the rule
      expect(result).not.toContain('\n  ');
    });
  });

  describe('generateCSSUsageExample', () => {
    it('returns usage example with CSS variables', () => {
      const result = generateCSSUsageExample();

      expect(result).toContain('.button');
      expect(result).toContain('var(--tekton-primary-500)');
      expect(result).toContain(':hover');
      expect(result).toContain(':focus');
    });
  });
});
